import {test} from 'node:test';import assert from 'node:assert/strict';import {listDestinations,listTagDestinations,openDestination,currentAccountId} from '../extension/navigation.js';import {captureSelection} from '../extension/selection.js';import {mailFixture} from './mail-fixture.js';
function nav(folders,{unified=false}={}){const calls=[];return {calls,api:{accounts:{list:async()=>[{id:'a',name:'OpenADR'},{id:'b',name:'Personal'}]},folders:{query:async q=>{if(q.isUnified)return unified?[{id:'smart/inbox'}]:[];if(q.isTag)return [{id:'tag/work',name:'Work'}];return folders.filter(f=>f.accountId===q.accountId&&f.specialUse.includes(q.specialUse[0]));}},mailTabs:{get:async id=>{if(id!==7)throw Error('not a mail tab');return {id:7,displayedFolder:{accountId:'b'}};},update:async(...a)=>calls.push(['update',...a]),setQuickFilter:async(...a)=>calls.push(['filter',...a])}}};}
const folders=[{id:'a/inbox',name:'Caixa de entrada',accountId:'a',specialUse:['inbox']},{id:'b/inbox',accountId:'b',specialUse:['inbox']},{id:'b/sent',accountId:'b',specialUse:['sent']}];
test('localizedInboxUsesFolderType',async()=>{const {api}=nav(folders);const d=await listDestinations(api);assert.deepEqual(d.filter(x=>x.rank===1).map(x=>[x.title,x.folderId]),[['Go to Inbox · OpenADR','a/inbox'],['Go to Inbox · Personal','b/inbox']]);});
test('unifiedSelectionUsesOriginalAccount',async()=>{const f=mailFixture();const s=await captureSelection(f.api,7);assert.deepEqual(s.messageIds,[1,2]);assert.equal((await f.api.messages.get(s.messageIds[1])).folder.accountId,'b');});
test('current account is marked and unified inbox comes first when Thunderbird has one',async()=>{const {api}=nav(folders,{unified:true});const d=await listDestinations(api,await currentAccountId(api,7));assert.equal(d[0].title,'Go to Unified Inbox');assert.ok(d.some(x=>x.title==='Go to Inbox · Personal (current)'));assert.ok(d.some(x=>x.title==='Go to Sent · Personal (current)'));assert.ok(!d.some(x=>x.title.includes('OpenADR (current)')));});
test('no unified inbox command when Thunderbird has no unified folders',async()=>{const {api}=nav(folders);assert.ok(!(await listDestinations(api)).some(x=>x.id==='go:unified'));});
test('navigation only changes the displayed folder of a mail tab',async()=>{const {api,calls}=nav(folders);assert.equal((await openDestination(api,7,{folderId:'b/sent'})).ok,true);assert.deepEqual(calls,[['update',7,{displayedFolder:'b/sent'}]]);assert.equal((await openDestination(api,9,{folderId:'b/sent'})).code,'not-a-mail-tab');assert.equal(calls.length,1);});
test('tag navigation opens the virtual tag folder when present, else filters the current folder',async()=>{const {api,calls}=nav(folders);const d=await listTagDestinations(api,[{key:'$label2',tag:'Work'},{key:'$label5',tag:'Later'}]);assert.equal(d[0].folderId,'tag/work');assert.equal(d[1].folderId,undefined);await openDestination(api,7,d[1]);assert.deepEqual(calls,[['filter',7,{show:true,tags:{mode:'all',tags:{$label5:true}}}]]);});
