import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createReferenceView} from '../extension/referenced-messages.js';
import {fixture as background} from './background-fixture.js';
function fixture(){
 const folder={id:'native-inbox',accountId:'a',name:'Inbox'};
 const headers=new Map([[1,{id:1,headerMessageId:'anchor@x',folder,subject:'Selected',author:'Sender <one@example.invalid>',date:new Date('2026-10-06T10:00:00Z')}],[2,{id:2,headerMessageId:'parent@x',folder,subject:'Earlier <img>',author:'Parent',date:new Date('2026-10-05T10:00:00Z')}]]);
 let selected=[1],time=0;const calls=[];
 const api={runtime:{getURL:p=>'moz-extension://test/'+p},tabs:{create:async p=>{calls.push(['tab',p]);return {id:8,windowId:3};}},accounts:{list:async()=>[{id:'a',name:'Work'}]},mailTabs:{getSelectedMessages:async()=>({messages:selected.map(id=>({id})),id:null})},messages:{get:async id=>{if(!headers.has(id))throw Error('gone');return structuredClone(headers.get(id));},getHeaders:async(...args)=>{calls.push(['headers',...args]);return {references:['<parent@x> <anchor@x>'],'in-reply-to':['<parent@x>']};},getFull:async()=>assert.fail('Bodies must not be fetched'),query:async q=>{calls.push(['query',q]);return {messages:[...headers.values()].filter(h=>h.folder.id===q.folderId&&h.headerMessageId===q.headerMessageId).map(h=>structuredClone(h)),id:null};},continueList:async()=>assert.fail('Unexpected pagination'),abortList:async id=>calls.push(['abort',id])},messageDisplay:{open:async p=>{calls.push(['native',p]);return {id:9};}}};
 const service=createReferenceView(api,{now:()=>time});const context={tabId:7,windowId:3,selection:{tabId:7,source:'mailTab',messageIds:[1]}};
 const sender={tab:{id:8,windowId:3},url:api.runtime.getURL('ui/references.html')};
 const open=()=>service.open(context);
 const token=()=>new URL(calls.find(c=>c[0]==='tab')[1].url).searchParams.get('token');
 const init=()=>service.handle({type:'references:init',token:token()},sender);
 const run=id=>service.handle({type:'references:open',token:token(),messageId:id},sender);
 return {api,headers,calls,service,context,sender,open,init,run,token,setSelection:v=>{selected=v;},setTime:v=>{time=v;}};
}
test('launch captures original window and opens a tab with an ephemeral token',async()=>{const f=fixture();assert.equal((await f.open()).ok,true);assert.equal(f.calls[0][0],'tab');assert.equal(f.calls[0][1].windowId,3);assert.ok(f.token());});
test('list returns selected and unique same-folder references as metadata only',async()=>{const f=fixture();await f.open();const r=await f.init();assert.equal(r.ok,true);assert.deepEqual(r.items.map(i=>i.id),[1,2]);assert.equal(r.items[0].selected,true);assert.equal(r.items[1].subject,'Earlier <img>');assert.deepEqual(r.scope,{accountName:'Work',folderName:'Inbox'});assert.deepEqual(f.calls.find(c=>c[0]==='headers'),['headers',1,{decodeHeaders:false}]);assert.equal(r.items[1].folder,undefined);});
test('exact selected reference opens by native ID in the captured window',async()=>{const f=fixture();await f.open();await f.init();assert.equal((await f.run(2)).ok,true);assert.deepEqual(f.calls.find(c=>c[0]==='native'),['native',{messageId:2,location:'tab',active:true,windowId:3}]);});
test('changed source selection rejects launching a stale palette',async()=>{const f=fixture();f.setSelection([2]);assert.equal((await f.open()).code,'selection-changed');assert.equal(f.calls.length,0);});
test('multiple selected messages do not launch an inferred conversation',async()=>{const f=fixture();f.context.selection.messageIds=[1,2];f.setSelection([1,2]);assert.equal((await f.open()).code,'select-one-message');assert.equal(f.calls.length,0);});
test('getHeaders absence gates the view without a body fallback',async()=>{const f=fixture();delete f.api.messages.getHeaders;assert.equal((await f.open()).code,'references-unavailable');assert.equal(f.calls.length,0);});
test('external or accountless anchor is rejected',async()=>{const f=fixture();f.headers.get(1).folder=undefined;assert.equal((await f.open()).code,'references-unavailable');assert.equal(f.calls.length,0);});
test('reference query verifies exact folder account and RFC header instead of trusting returned matches',async()=>{const f=fixture();f.api.messages.query=async()=>({messages:[{...f.headers.get(2),folder:{id:'other',accountId:'a'}},{...f.headers.get(2),headerMessageId:'parent@x.extra'},{...f.headers.get(2),folder:{...f.headers.get(2).folder,accountId:'b'}}],id:null});await f.open();const r=await f.init();assert.deepEqual(r.items.map(i=>i.id),[1]);assert.equal(r.issues.missing,1);});
test('duplicate exact header matches are ambiguous and excluded',async()=>{const f=fixture();f.headers.set(3,{...f.headers.get(2),id:3});await f.open();const r=await f.init();assert.deepEqual(r.items.map(i=>i.id),[1]);assert.equal(r.issues.ambiguous,1);});
test('pagination checks later duplicate and aborts outstanding cursor',async()=>{const f=fixture();f.api.messages.query=async()=>({messages:[f.headers.get(2)],id:'page'});f.api.messages.continueList=async()=>({messages:[{...f.headers.get(2),id:3}],id:'remaining'});await f.open();const r=await f.init();assert.equal(r.issues.ambiguous,1);assert.deepEqual(f.calls.find(c=>c[0]==='abort'),['abort','remaining']);});
test('pagination failure after a first match does not claim a unique result',async()=>{const f=fixture();f.api.messages.query=async()=>({messages:[f.headers.get(2)],id:'page'});f.api.messages.continueList=async()=>{throw Error('offline');};await f.open();const r=await f.init();assert.deepEqual(r.items.map(i=>i.id),[1]);assert.equal(r.issues.unavailable,1);assert.ok(f.calls.some(c=>c[0]==='abort'));});
test('offline anchor headers retain selected message with an explicit unavailable count',async()=>{const f=fixture();f.api.messages.getHeaders=async()=>{throw Error('offline');};await f.open();const r=await f.init();assert.equal(r.ok,true);assert.deepEqual(r.items.map(i=>i.id),[1]);assert.equal(r.issues.headersUnavailable,true);assert.equal(r.issues.unavailable,0);});
test('newer unrelated same-subject messages are never queried or included',async()=>{const f=fixture();f.headers.set(3,{...f.headers.get(1),id:3,headerMessageId:'newer@x'});await f.open();const r=await f.init();assert.deepEqual(r.items.map(i=>i.id),[1,2]);assert.deepEqual(f.calls.filter(c=>c[0]==='query').map(c=>c[1]),[{folderId:'native-inbox',headerMessageId:'parent@x'}]);});
test('header bound reports truncation and queries only the latest fifty unique IDs',async()=>{const f=fixture();f.api.messages.getHeaders=async()=>({references:[Array.from({length:55},(_,i)=>'<m'+i+'@x>').join(' ')]});await f.open();const r=await f.init();const q=f.calls.filter(c=>c[0]==='query');assert.equal(q.length,50);assert.equal(q[0][1].headerMessageId,'m5@x');assert.equal(r.issues.truncated,5);});
test('moved or reused anchor is rejected before metadata or opening',async()=>{const f=fixture();await f.open();f.headers.get(1).headerMessageId='reused@x';assert.equal((await f.init()).code,'references-stale');assert.equal(f.calls.filter(c=>c[0]==='headers').length,0);});
test('opening must be initialized and limited to the returned allowlist',async()=>{const f=fixture();await f.open();assert.equal((await f.run(2)).code,'unknown-reference');await f.init();assert.equal((await f.run(999)).code,'unknown-reference');assert.equal((await f.run('2')).code,'unknown-reference');assert.equal(f.calls.filter(c=>c[0]==='native').length,0);});
test('moved reference cannot open even when its transient ID still resolves',async()=>{const f=fixture();await f.open();await f.init();f.headers.get(2).folder={id:'elsewhere',accountId:'a'};assert.equal((await f.run(2)).code,'references-stale');assert.equal(f.calls.filter(c=>c[0]==='native').length,0);});
test('new duplicate reference invalidates a previously unique choice',async()=>{const f=fixture();await f.open();await f.init();f.headers.set(3,{...f.headers.get(2),id:3});assert.equal((await f.run(2)).code,'references-stale');assert.equal(f.calls.filter(c=>c[0]==='native').length,0);});
test('source selection change after launch does not retarget the anchored list',async()=>{const f=fixture();await f.open();f.setSelection([2]);assert.deepEqual((await f.init()).items.map(i=>i.id),[1,2]);assert.equal((await f.run(1)).ok,true);assert.equal(f.calls.find(c=>c[0]==='native')[1].messageId,1);});
test('wrong tab or window cannot use another navigator token',async()=>{const f=fixture();await f.open();for(const tab of [{id:9,windowId:3},{id:8,windowId:4}])assert.equal((await f.service.handle({type:'references:init',token:f.token()},{...f.sender,tab})).code,'context-expired');});
test('expired or closed navigator session cannot list or open',async()=>{const f=fixture();await f.open();f.setTime(300001);assert.equal((await f.init()).code,'context-expired');const g=fixture();await g.open();g.service.forget(8);assert.equal((await g.init()).code,'context-expired');});
test('native open failure permits retry without claiming success',async()=>{const f=fixture();await f.open();await f.init();let n=0;f.api.messageDisplay.open=async()=>{if(!n++)throw Error('offline');return {id:9};};assert.equal((await f.run(2)).code,'message-open-failed');assert.equal((await f.run(2)).ok,true);});
test('concurrent native open is rejected while the first request is pending',async()=>{const f=fixture();await f.open();await f.init();let resume,entered;const started=new Promise(r=>{entered=r;}),wait=new Promise(r=>{resume=r;});f.api.messageDisplay.open=async()=>{entered();await wait;return {id:9};};const first=f.run(2);await started;const second=await f.run(1);resume();assert.equal(second.code,'context-busy');assert.equal((await first).ok,true);});
test('navigator closed during header read discards metadata',async()=>{const f=fixture();await f.open();let resume,entered;const started=new Promise(r=>{entered=r;}),wait=new Promise(r=>{resume=r;});f.api.messages.getHeaders=async()=>{entered();await wait;return {references:['<parent@x>']};};const first=f.init();await started;f.service.forget(8);resume();assert.equal((await first).code,'context-expired');});
test('background palette gates references and uses captured window for the new view',async()=>{const f=await background();f.api.messages.getHeaders=async()=>({});f.api.messages.query=async()=>({messages:[],id:null});f.messages.get(1).headerMessageId='anchor@x';f.api.tabs.create=async p=>{f.calls.push(['tab',p]);return {id:8,windowId:1};};f.api.messageDisplay={open:async()=>({id:9})};const data=await f.request({type:'palette:init'});assert.equal(data.commands.find(c=>c.id==='references')?.available,true);assert.equal((await f.request({type:'command:run',token:data.token,commandId:'references'})).ok,true);assert.equal(f.calls.at(-1)[1].windowId,1);});

test('target moved during unique reference lookup is rechecked before native open',async()=>{
 const f=fixture();await f.open();await f.init();const query=f.api.messages.query;
 f.api.messages.query=async q=>{const r=await query(q);f.headers.get(2).folder={id:'elsewhere',accountId:'a'};return r;};
 assert.equal((await f.run(2)).code,'references-stale');assert.equal(f.calls.filter(c=>c[0]==='native').length,0);
});
test('initial page request waits for native tab creation before checking owner',async()=>{
 const f=fixture();let pending;
 f.api.tabs.create=async p=>{f.calls.push(['tab',p]);pending=f.service.handle({type:'references:init',token:new URL(p.url).searchParams.get('token')},f.sender);return {id:8,windowId:3};};
 assert.equal((await f.open()).ok,true);assert.equal((await pending).ok,true);
});
test('query page bound aborts an incomplete lookup instead of claiming missing',async()=>{
 const f=fixture();let n=0;f.api.messages.query=async()=>({messages:[],id:'loop'});f.api.messages.continueList=async()=>{n++;return {messages:[],id:'loop'};};
 await f.open();const r=await f.init();assert.equal(r.issues.unavailable,1);assert.equal(r.issues.missing,0);assert.equal(n,19);assert.ok(f.calls.some(c=>c[0]==='abort'));
});
test('direct parent remains inside the reference limit regardless of native header property order',async()=>{
 const f=fixture();f.api.messages.getHeaders=async()=>({'in-reply-to':['<direct@x>'],references:[Array.from({length:55},(_,i)=>'<m'+i+'@x>').join(' ')]});
 await f.open();const r=await f.init();const queries=f.calls.filter(c=>c[0]==='query');assert.equal(queries.length,50);assert.equal(queries.at(-1)[1].headerMessageId,'direct@x');assert.equal(r.issues.truncated,6);
});
test('source tab closure leaves the explicitly anchored navigator usable',async()=>{const f=fixture();await f.open();f.service.forget(7);assert.equal((await f.init()).ok,true);});
test('navigator expires during a lookup and returns no usable metadata',async()=>{const f=fixture();await f.open();const query=f.api.messages.query;f.api.messages.query=async q=>{f.setTime(300001);return query(q);};assert.equal((await f.init()).code,'context-expired');});
test('other extension page cannot use the reference token even in the same owner tab',async()=>{const f=fixture();await f.open();assert.equal((await f.service.handle({type:'references:init',token:f.token()},{...f.sender,url:f.api.runtime.getURL('ui/settings.html')})).code,'context-expired');});
