import {test} from 'node:test';import assert from 'node:assert/strict';import {createSendAndArchive} from '../extension/send-and-archive.js';
function fixture(){const calls=[];return {calls,api:{compose:{getComposeDetails:async()=>({type:'reply',identityId:'identity',relatedMessageId:42}),sendMessage:async(id,options)=>{calls.push(['send',id,options]);return {mode:'sendNow',headerMessageId:'sent-id',messages:[]};}},messages:{get:async()=>({id:42}),archive:async ids=>calls.push(['archive',ids])}}};}
test('successfulImmediateSendArchivesOriginal',async()=>{const f=fixture();const r=await createSendAndArchive(f.api).run(7);assert.equal(r.ok,true);assert.deepEqual(f.calls,[['send',7,{mode:'sendNow'}],['archive',[42]]]);});
test('failedSendDoesNotArchive',async()=>{const f=fixture();f.api.compose.sendMessage=async()=>{throw Error();};assert.equal((await createSendAndArchive(f.api).run(7)).ok,false);assert.deepEqual(f.calls,[]);});
test('queuedSendDoesNotArchive',async()=>{const f=fixture();f.api.compose.sendMessage=async()=>({mode:'sendLater'});assert.equal((await createSendAndArchive(f.api).run(7)).code,'not-confirmed-sent');assert.deepEqual(f.calls,[]);});
test('duplicateClickDoesNotSendTwice',async()=>{const f=fixture();let release;f.api.compose.sendMessage=async()=>{f.calls.push(['send']);return new Promise(r=>{release=r;});};const service=createSendAndArchive(f.api);const first=service.run(7);await new Promise(r=>setImmediate(r));assert.equal((await service.run(7)).code,'already-running');release({mode:'sendNow',headerMessageId:'x'});await first;assert.equal(f.calls.filter(c=>c[0]==='send').length,1);});
test('archiveFailureDoesNotResend',async()=>{const f=fixture();f.api.messages.archive=async()=>{throw Error();};const service=createSendAndArchive(f.api);assert.equal((await service.run(7)).code,'sent-archive-failed');assert.equal((await service.run(7)).code,'already-running');assert.equal(f.calls.length,1);});
test('missingRelatedMessageDisablesAction',async()=>{const f=fixture();f.api.compose.getComposeDetails=async()=>({type:'new'});assert.equal((await createSendAndArchive(f.api).run(7)).code,'not-a-reply');assert.deepEqual(f.calls,[]);});
test('closedComposeStillUsesCapturedOriginal',async()=>{const f=fixture();let reads=0;f.api.compose.getComposeDetails=async()=>{reads++;if(reads>1)throw Error('closed');return {type:'reply',relatedMessageId:42};};await createSendAndArchive(f.api).run(7);assert.equal(reads,1);assert.deepEqual(f.calls[1],['archive',[42]]);});
test('ambiguous success never archives',async()=>{const f=fixture();f.api.compose.sendMessage=async()=>({mode:'sendNow'});assert.equal((await createSendAndArchive(f.api).run(7)).code,'not-confirmed-sent');assert.deepEqual(f.calls,[]);});
test('send rejection remains locked until the compose tab closes',async()=>{const f=fixture();let sends=0;f.api.compose.sendMessage=async()=>{sends++;throw Error('server may have accepted');};const service=createSendAndArchive(f.api);await service.run(7);assert.equal((await service.run(7)).code,'already-running');assert.equal(sends,1);service.forget(7);await service.run(7);assert.equal(sends,2);});
test('ambiguous send cannot be retried automatically',async()=>{const f=fixture();f.api.compose.sendMessage=async()=>({mode:'sendNow'});const service=createSendAndArchive(f.api);await service.run(7);assert.equal((await service.run(7)).code,'already-running');});
